[build]
rustflags = ["-C", "link-arg=-Wl,-rpath,/home/ubuntu/repos/angr/.venv/lib/python3.12/site-packages/z3/lib"]

[env]
Z3_SYS_Z3_HEADER = "/home/ubuntu/repos/angr/.venv/lib/python3.12/site-packages/z3/include/z3.h"
